[packages.versioning]
versioned_files = ["crates/knope-versioning/Cargo.toml"]
changelog = "crates/knope-versioning/CHANGELOG.md"

[packages.config]
versioned_files = ["crates/knope-config/Cargo.toml"]
changelog = "crates/knope-config/CHANGELOG.md"

[packages.knope]
versioned_files = ["crates/knope/Cargo.toml"]
changelog = "CHANGELOG.md"
extra_changelog_sections = [{ name = "Documentation", types = ["docs"] }]

[[packages.knope.assets]]
path = "artifacts/knope-x86_64-unknown-linux-musl.tgz"

[[packages.knope.assets]]
path = "artifacts/knope-x86_64-pc-windows-msvc.tgz"

[[packages.knope.assets]]
path = "artifacts/knope-x86_64-apple-darwin.tgz"

[[packages.knope.assets]]
path = "artifacts/knope-aarch64-apple-darwin.tgz"

[github]
owner = "knope-dev"
repo = "knope"

[bot.releases]
enabled = true
