name: Publish crates

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish-crates:
    if:  (github.head_ref == 'knope/release' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-binstall
        run: |
          gh release download "v${BINSTALL_VERSION}" --repo "cargo-bins/cargo-binstall" --pattern "cargo-binstall-x86_64-unknown-linux-musl.tgz"
          tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          cp cargo-binstall $HOME/.cargo/bin
        env:
          GH_TOKEN: ${{ github.token }}
          BINSTALL_VERSION: 1.8.0
      - name: Install cargo-release
        run: cargo binstall --no-confirm cargo-release
      - run: cargo release publish --workspace --execute
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
